# Utilisation de l'image PHP Apache
FROM php:apache

RUN a2enmod headers

# Copier les fichiers de votre application dans le conteneur
COPY . /var/www/html/
# Exposer le port 80 du conteneur
EXPOSE 80
